services:
  discord-playtime-tracker-backend:
    build:
      context: ./backend

  discord-playtime-tracker-frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: /api
        VITE_GUILD_ID: ${VITE_GUILD_ID}
